### ISSUE TITLE
Support emoji's and autolinking in HipChat

### ISSUE THREAD

**Issue by vanstee** [operable/cog#1094]
Right now Slack supports emoji and autolinking, but when the bot posts responses in HipChat we always just get the raw text. We need to also verify that this still works after a redirect.

<img width="809" alt="screen shot 2016-10-25 at 3 16 11 pm" src="https://cloud.githubusercontent.com/assets/228734/19700669/3ae87e9c-9ac6-11e6-9842-cd9e76061afc.png">

**Comment by kevsmith** [comment]
Dumping my research information in here as I go:

1. [send_room_notification](https://www.hipchat.com/docs/apiv2/method/send_room_notification) is the API call Cog currently uses to send responses via HipChat. This API was chosen because it supports formatted output.
1. [send_room_message](https://www.hipchat.com/docs/apiv2/method/send_room_message) will link-ify @-mentions and replace text emojis with their graphical counterparts. It doesn't support any other formatting options and limits payload size to 1000 chars or less.

**Comment by vanstee** [comment]
Worth mentioning that `send_message` also supports emoji where `send_room_notification` does not.

**Comment by kevsmith** [comment]
I modified the HipChat provider to send responses via XMPP instead of HipChat's API to see if we could use extended message namespaces, specifically the HTML namespace, to send formatted messages and also get emoji and @-mention support. Looks like the answer is 'no' based on this log output:

```
<message from='479543_bot-testing@conf.hipchat.com'
  type='error'
  id='76d0'
  to='479543_4357806@chat.hipchat.com/none||proxy|pubproxy-d400.hipchat.com|5292'>
<html xmlns='http://jabber.org/protocol/xhtml-im'><body xmlns='http://www.w3.org/1999/xhtml'><body><strong>Command Error</strong><br/><br/><strong>Started:</strong> 2016-10-31T16:59:29Z<br/><strong>Pipeline ID:</strong> 2b82c122d6f24035b5554518afcd389e<br/><strong>Pipeline:</strong> hello<br/><strong>Caller:</strong> @KevinSmith<br/><br/><br/><br/>The specific error was:<br/><br/><pre>Command 'hello' not found in any installed bundle.</pre></body></body></html>
<error code='501' type='cancel'>
  <feature-not-implemented xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
</error>
</message>
```

**Comment by kevsmith** [comment]
I believe the underlying culprit is [HipChat's](https://answers.atlassian.com/questions/38838139/xmpp-htmltext) lack of support for XMPP's `xhtml-im` extension for `MUC` messages.

Moving this ticket to 0.17 to give us time to consider how best to resolve and solicit opinions from the community.

**Comment by christophermaier** [comment]
After digging around for a bit, it does indeed seem that it's down to HipChat not supporting `xhtml-im` for room messages. You can do it for 1-on-1 messages though.

See https://jira.atlassian.com/browse/HCPUB-1130

A workaround isn't immediately obvious, and it doesn't seem that dropping all formatting from Cog's Hipchat messages in order to gain emoji and autolinking is a great tradeoff right now. We'll continue to monitor the situation, but will close this issue for now.
