### ISSUE TITLE
Human friendly trigger URLs

### ISSUE THREAD

**Issue by 0xdiba** [operable/cog#1095]
Would be useful if we could set the uuid or just the trigger url for created triggers.

**Comment by Shelton** [comment]
Great question + lead me to learning something new about our triggers. I just talked to @imbriaco about this and he mentioned, "The problem with that is that part of the long URL is there as an authentication mechanism." I hope that helps @0xdiba

**Comment by imbriaco** [comment]
Hi @0xdiba, could you explain more about your use case?

I'm a little bit worried about making more easily guessable trigger URLs since they often have `as_user` set and run a pipeline on behalf of that user with no other authentication. Granted, an embedded UUID is not actually the epitome of security, but it's better than nothing. :)

Understanding what your use case would be might help me wrap my head around the idea more though.

**Comment by jesselang** [comment]
Closing due to age.
