### ISSUE TITLE
Greenbar segfaults with a specific bundle config

### ISSUE THREAD

**Issue by agis-** [operable/cog#1141]
We're on Cog 0.16.0 and asking for `!help` of the following command in a bundle triggers a segfault in https://github.com/operable/greenbar:

    eapp:
      executable: "/foo/cogy"
      description: Search for electronic applications by shop or company name, VAT,
        url and email!
      rules:
      - allow
      arguments: "<query>"
      examples: |-
        Searching by shop code:
  
        ```
        !skr:eapp e-wifa
        ```
  
        Searching by VAT num:
  
        ```
        !skr:eapp 064661990
        ```
  
        Searching by company name:
  
        ```
        !skr:eapp 'e-wifa Ο.Ε.'
        ```
  
        Searching by URL:
  
        ```
        !skr:eapp http://www.e-wafa.gr
        ```
  
        Searching by incharge mail:
  
        ```
        !skr:eapp @e-wafa.gr
        ```

**Comment by kevsmith** [comment]
I've tried running the template on my laptop (OS X 10.10.5) and in the Alpine Linux-based Cog 0.16 container and haven't seen the segfault. I have a few questions :)

1. What Linux distro are you using?
1. How are you installing and deploying Cog?
1. Would you be willing to try a debug build of Cog and Greenbar if we built it?

**Comment by agis-** [comment]
1. Debian jessie
2. We compile from source and we use systemd to monitor the processes
3. Yes!

Here's an strace dump: https://gist.github.com/agis-/0a3a6ee4f291b27ce7ad7ae19e710c32

**Comment by agis-** [comment]
I think it's because of the triple backticks in the `examples` section. I took out the backticks and it worked fine.

Cog already wraps the section in triple backticks itself, so can it be possible that the additional triple backticks cause Greenbar to crash?

**Comment by kevsmith** [comment]
I was finally able to repro the segfault. The root cause was a bad assumption I had about how hoedown calls registered markdown callback functions. Prior to the fix the `greenbar_markdown` NIF library checked for empty `hoedown_buffer`s by inspecting the buffer size like so:

```
static void handle_blockcode(hoedown_buffer *ob, 
                                                const hoedown_buffer *text, 
                                                const hoedown_buffer *lang, 
                                                const hoedown_renderer_data *data) {
  if (text->size > 1) {
    // markdown processing happens here
  }
}
```

This generally works except in the case of degenerate input like (ticks replaced with single quotes because Markdown in Markdown):

**Comment by kevsmith** [comment]
Markdown parsing. Oy.

**Comment by kevsmith** [comment]
I was finally able to repro the segfault. The root cause was a bad assumption I had about how hoedown calls registered markdown callback functions. Prior to the fix the `greenbar_markdown` NIF library checked for empty `hoedown_buffer`s by inspecting the buffer size like so:

```
static void handle_blockcode(hoedown_buffer *ob, 
                                                const hoedown_buffer *text, 
                                                const hoedown_buffer *lang, 
                                                const hoedown_renderer_data *data) {
  if (text->size > 1) {
    // markdown processing happens here
  }
}
```

This general works except in the case of degenerate input like nested triple ticks. I'm using the term 'degenerate' here because, afaict, codeblocks do not nest in Markdown and behave purely as open/close pairs.

In this case hoedown will call the registered blockcode callback function with a null `hoedown_buffer` reference.

**Comment by kevsmith** [comment]
The fix is to modify the callback function to check for null buffer refs like so:

```
if (text == nullptr || text->size == 0)  {
  return;
}
```
