### ISSUE TITLE
Add support for Amazon's EC2 Container Registry (ECR) to Relay

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#1281]
Cog users wishing to access container images stored in Amazon's [EC2 Container Registry](https://aws.amazon.com/documentation/ecr/) from Relay will run into issues because a `docker login` yields a token that is effective for only 12 hours. With Relay's current implementation, you'd likely need to resort to things like restart the Relay process on a schedule in order for it to continue working.

Relay should have some smarts to contend with this use case. @kevsmith suggested exposing ECR support as a new engine within Relay.

**Comment by christophermaier** [comment]
Peter Norton in Cog Slack mentioned https://github.com/awslabs/amazon-ecr-credential-helper. Perhaps adding support for a Docker [credStore](https://docs.docker.com/engine/reference/commandline/login/#/credentials-store) could be a way to address this issue, and could be useful beyond just ECR.

**Comment by pcn** [comment]
This branch implements a limited functionality where *only* ECR can be used: https://github.com/pcn/go-relay/tree/how-would-this-work.  The limitation with that is that any images that would be used need to be loaded into ECR.  Requesting images that aren't in the provided ECR registry will result in a referrel to dockerhub being returned, and then trying to get from dockerhub will fail because the ECR creds will be preferred.

**Comment by christophermaier** [comment]
This issue was moved to operable/go-relay#74
