### ISSUE TITLE
Extract a "pluck" command

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#255]
Currently, the `filter` command performs both filtering and projection / "plucking". These should be separate commands.

The new "pluck" command (think Rails and ActiveRecord [see, e.g., http://gavinmiller.io/2013/getting-to-know-pluck-and-select/]) effectively performs the `--return` option functionality from `filter`. That is, `pluck foo` would return inputs with all but their `foo` keys removed (e.g., `{"foo": "blah"}`), `pluck foo bar` would return just the `foo` and `bar` keys (e.g., `{"foo": "blah", "bar": "blah"}`), and so on. (Could instead call it like `pluck --fields=foo,bar`, perhaps)

`pluck` should be a non-enforcing, multiple execution function with "all" binding semantics.

Removing the `--return` functionality from the `filter` command should be part of this work, as well.

**Comment by lhaskins** [comment]
In a conversation about filter, there was some discussion about how this command should be executed. It should essentially perform the same action that the usage of the `return` option would perform in the previous filter command before the completion of Issue #256.

In the same way that filter has the capability to traverse a path, pluck should be able to do the same. Initially, the first pass was to do the equivalent of return adding in the ability to handle JSON paths. 

It should be noted that the fields must be escaped when handling paths that are quoted. For example, in order to access the following: `-fields=foo,"bar.baz"` the quotes must be escaped to look like the following: `-fields="foo,\"bar.baz\""`.

**Comment by lhaskins** [comment]
Given the following command: ```seed '[{"foo":{"bar":{"baz":"stuff"}, "one": 1}, "qux": "one"}, {"foo": {"bar":{"baz":"me"}}, "qux": "two"}]' | pluck --paths="qux,'foo.bar.baz'"```

Should the output be collapsed such that it would look like:
```
[{
  "qux": "one",
  "foo.bar.baz": "stuff"
},
{
  "qux": "two",
  "foo.bar.baz": "me"
}]
```
or
```
{
  "qux": "one",
  "foo": {
    "one": 1,
    "bar": {
      "baz": "stuff"
    }
  }
},
{
  "qux": "two",
  "foo": {
    "bar": {
      "baz": "me"
    }
  }
}
```
Or a third option where there is a ```collapse``` flag that collapses the output into a single level with the default set to display the expanded map

**Comment by lhaskins** [comment]
Closing since changes in piper/executor may make this command unnecessary.
