### ISSUE TITLE
Write our own Slack RTM and API clients

### ISSUE THREAD

**Issue by vanstee** [operable/cog#289]
Right now we're using a tiny rtm library that has some weird edge cases and missing functionality along with custom http api calls for everything else. It'd be nice to implement our own so we have better control over our interface with Slack and can more easily make changes in the future.

**Comment by kevsmith** [comment]
We should check to see if there are any decent Slack API (meaning their REST interface) clients before we write our own. The code we have now was written when I couldn't find a decent REST client. Slack adoption has grown by leaps and bounds since then so there's a chance a decent client might exist now.

**Comment by kevsmith** [comment]
I'm moving this out of milestone 0.3 until we have a clearer picture of the work involved.

**Comment by kevsmith** [comment]
Closing due to lack of specifics and this work getting subsumed into pending chat adapter refactor.
