### ISSUE TITLE
Template using triple mustache returns extra mustaches

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#324]
When using triple mustaches in a template, the JSON output generated returns extra braces enclosing the output.

Given the following template:
"""
{{^.}}No items found{{/.}}
{{#.}}
```{{{.}}}```
{{/.}}
"""
With raw output:
"""{"foo": {"bar.qux": {"baz": "stuff"}}}"""

Using the template, generates:
"""{{{"foo": {"bar.qux": {"baz": "stuff"}}}}}"""

**Comment by mpeck** [comment]
It looks like the issue here has to do with a conflict in piper. Piper defines a protocol `String.Chars.to_string` for `Elixir.Map` that FuManchu uses to render the template properly (https://github.com/operable/piper/blob/master/lib/piper/command/ast/chars/literals_chars.ex#L32-L39). The Piper implementation adds extra braces to the start and end of the resulting string.

The plan is to remove the implementation from Piper, since it's a bit too generic, and add an implementation for `Piper.String.Chars` to be called explicitly. We'll then need to add a similar struct to FuManchu.

**Comment by mpeck** [comment]
Note: dependent on #286

**Comment by mpeck** [comment]
dependent on #340
