### ISSUE TITLE
Reorganize Cog as an umbrella project

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#325]
Propagating bug fixes and new features thru the codebase has become quite painful given our current multi-repo structure. Reorganizing as an umbrella project allows us to centralize code in a single repo (aka "monorepo") and has the potential to simplify packaging and deployment for Docker and EC2 AMIs.

Do not start work on this without checking in with Kevin or Mark first.

**Comment by vanstee** [comment]
@kevsmith Did you have a branch of your work pushed anywhere?

**Comment by vanstee** [comment]
Oh nvm, found it: https://github.com/operable/cog/tree/kevsmith/umbrella

**Comment by vanstee** [comment]
This is still possible but requires more effort than we wanted to spend at the moment. Here are the things we'll need to do to accomplish this in the future.

- Rework config so we're treating it as a dumb keyword list rather than calling functions and such to generate values
- Move system env var lookup into code and out of the config files (passing in `{:system, "ENV_VAR"}` seems like a good convention here
- Build releases with `exrm` which will allow us to include only the parts of the app that we need when running cog and relay separately.
- Fix dep version mismatches between repos (we'll need a few more overrides to get this all working properly)

**Comment by kevsmith** [comment]
We've taken several runs at this and ran into issues each time. Closing.
