### ISSUE TITLE
Consume and respond to external events

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#344]
Think of kicking off a command pipeline in response to an external webhook (e.g., when a PR is created or merged in Github).

**Comment by kevsmith** [comment]
# Motivation

Many workflow automation use cases require external information sent via non-chat channels. A couple of obvious examples are GitHub's deployment notifications and build status notifications from CI services like Jenkins or Travis. Cog needs the ability to consume these events and process them with pipelines in order to provide a complete ChatOps automation solution.

# Summary

Cog will expose a standard API used to define and configure event hooks. Access to the API will be controlled via permissions consistent with how Cog already controls access to other administrative APIs like managing groups. Requests sent to a configured event hook will be processed by the defined Cog pipeline executing as the assigned user.

# Details

## Managing event hooks

Event hooks will be exposed via a REST API consistent with Cog's existing REST API.

#### Creating a new event hook 

- __URL:__ `POST /api/v1/event_hooks` (auth required) 
- __Body:__ JSON object with the fields listed below:
  - `pipeline` - Valid Cog pipeline or alias (string, required)
  - `as_user` - Username or email of assigned user (string, required)
  - `verbs` - One or more of `GET`, `POST`, `PUT` (list of strings, optional, default: `POST`)
  - `capture_headers` - List of headers to capture and forward to the target pipeline (list of strings, optional)
  - `active` - (boolean, optional, default: true)
  - `notes` - Descriptive notes about the event hook (string, optional) 
- __Returns:__ Fully populated JSON object described above with two additional fields:
  - `id` - UUID assigned to event hook (string)
  - `path` - Path to event hook using the format `/events_hooks/<hook_id>`

#### Retrieving a event hook definition

- __URL__: `GET /api/v1/event_hooks/<hook_id>` (auth required)
- __Returns__: Fully populated JSON object described in "Creating new event hook" including `id` and `path`.

#### Deleting a event hook definition

- __URL__: `DELETE /api/v1/event_hooks/<hook_id>` (auth required)
- __Returns__: Standard REST response

#### Updating a event hook definition

- __URL__: `PUT /api/v1/events/hooks/<hook_id>` (auth required)
- __Body__: Fully populated JSON object described in "Creating new event hook"
- __Returns__: Fully populated JSON object reflecting user edits

### Routing incoming events to event hooks

Cog will attempt to find a matching hook definition whenever it receives a request on a event hook-ish URL. If a definition is not found, Cog shall return a 404 with an informative error message such as "No event hook found". When a definition is found Cog shall execute the hook using the inbound HTTP request as input (see "Event hook execution").

### Event hook execution

Executing a pipeline or alias in the context of a event hook should be as similar as possible to direct user execution. For brevity's sake this section will describe the differences between event hook and user execution environments.

##### Pipeline Inputs

- Initial pipeline input is derived solely from the following data sourced from the triggering HTTP request
  - The request body, if any
  - Request parameters, if any
  - Captured headers, if any (stored under a top-level key `hook_headers`)
- The event hook id will be exposed in the command execution environment under the environment variable `COG_HOOK_ID`.

##### Pipeline Outputs

- Event hooks have their own dedicated adapter named `event_hook`. This allows users to use purpose-built templates for event hook output.
- By default pipeline output will be sent as a HTTP response to the originating hook request.
- The default output behavior can be overridden by specifying one or more redirect targets. Supporting standard output redirect allows Cog to send notification-driven messages to users and rooms.
- An additional redirect target, `hook_reply`, can be used in cases where users would like to generate messages _and_ send event hook responses. _Note: The example pipeline uses redirect targets from two different providers implying two different templates could be used._

````
jenkins_handler | update_build_status *> hook_reply dev
```

##### Status Codes

- Successful pipeline execution shall result in a 200 status code returned to the event hook caller.
- Pipeline execution failure shall result in a 500 status code returned to the event hook caller.¯

**Comment by kevsmith** [comment]
- [ ] #385

**Comment by kevsmith** [comment]
Late breaking revisions to the above write up:

- Capturing headers -- We will always capture all headers and include them in the pipeline execution environment as already described.
- Verbs -- We will only support `POST` requests.
- As user -- This field is now optional. If a user isn't specified for an event hook then the incoming request __must__ contain a valid user session token as per our REST API. In the event a session token is provided and `as_user` is specified then `as_user` shall be used.

**Comment by christophermaier** [comment]
Also, the `hook_reply` redirection target should be `here`, in keeping with the intended meaning of that target.

**Comment by christophermaier** [comment]
Initial Plan of Attack (much of which is laying groundwork)

 - [ ] Address #210
 - [ ] Allow redirects to have prefixes; implement "chat" prefix
 - [ ] Beef up error handling; consolidate and increase information
 - [ ] Allow pipeline ID to be passed into executor for audit logging purposes
 - [ ] Allow "seed context" to be passed into executor process
 - [ ] Add COG_ENV to audit logging for pipeline invocations
 - [ ] Create endpoint to listen for webhooks and drive implementation from that. Use Github + ngrok as first use case

**Comment by christophermaier** [comment]
Regarding endpoint implementation with Github and ngrok, see https://developer.github.com/webhooks/configuring/ for details.

By creating an endpoint to respond to external events before we've created the CRUD API for them, we can totally tease out the implementation and interaction with the executor. You could start by simply coding up an endpoint that responds at `/api/v1/event_hooks/00000000-0000-0000-0000-000000000000` with a hard-coded hook body; if we're doing Github, then perhaps with a simple pipeline along the lines of 

```
echo User $USER has just created a pull request in $REPO! Go check it out: $PR_HTTP_URL > chat:#general
```
(Any other event hook UUID could just be a 500 for now).

This allows us to get right to the meat of this feature. Writing CRUD endpoints is straightforward. This also allows us to sort out exactly what data is necessary to define an event hook; we've got a plan for this already, but that may change when we get to implementation.

Taking this approach should allow for faster iteration.
