### ISSUE TITLE
HTTP-based service endpoint for commands

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#358]
# Cog Services API

Cog services will be managed by a separate Phoenix endpoint named `Cog.PlatformServicesEndpoint`. Building the API as a separate endpoint instead of a separate Phoenix app was chosen to avoid packaging and reuse issues with Cog (since it was never designed to be a reusable library) and also reduce the coding effort. An endpoint-based implementation strikes a good balance between isolation, modularity, and speed of development without constraining future choices.

The endpoint will contain its own HTTP router with the majority of application logic contained in controllers and views. The root URL of the services API will be exported to the command runtime environment under the environment variable `COG_SERVICES_ROOT`. It shall be a valid URL starting with either `http://` or `https://`, depending on user configuration, followed by the host name or IP address and listening port number. Examples: `http://192.168.2.22:4005`, `https://mycog.somecorp.com:4100`.

## Authentication and Authorization

Cog will generate a unique pipeline token upon pipeline initialization. The token will correlate a pipeline to the calling user much like REST API tokens correlate REST API sessions to calling users. Pipeline tokens have a finite lifespan. Their expiration can be triggered by either the completion (regardless of status) of the owning pipeline or after 1.5x the maximum execution interval for a pipeline. As of 4/18/2016, this translates to a maximum lifespan of 90 seconds.

The token will be exported to the command runtime environment under the environment variable `COG_PIPELINE_TOKEN`. All calls to the Cog Service API _must_ include the token in their `Authorization` HTTP header like so: `Authorization: pipeline <token>`. Requests without a properly formed `Authorization` header or referencing an expired or invalid pipeline token will receive `401 Unauthorized`.

## Routes

The Services API provides an informational API to assist monitoring, service discovery, and service enumeration. These endpoints are listed below.

### /services/meta

Returns a JSON object describing Cog version, Cog Services API version, and basic information about each hosted service. The below JSON document can be used as a normative reference.

#### Request
```http
GET /services/meta HTTP/1.1
Authorization: pipeline 123456789
```

#### Response
```http
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: ...

{"info": 
  {
    "cog_version": "0.5.0",
    "cog_services_api_version": "1",
    "services": [{"name": "exec",
                  "version": "1.0"},
                 {"name": "memory",
                  "version": "1.0"}]
  }
}
```

### /services/meta/deployed/{service_name}

Returns a Swagger 2.0 compliant JSON description of the named service's API. A 404 status code shall be returned if the requested service doesn't exist.

**Comment by christophermaier** [comment]
Brain dump of implementation ideas, to proceed in concert with implementation of #396:

Since pipeline tokens and memory service are both short-lived volatile data, we'll use ETS tables instead of Postgres as a backing store. Create a supervisor that creates/owns the ETS tables for pipeline tokens and memory service. Make them public, but not named ("security through obscurity"). Hand the TID into child processes that mediate access to the tables. If those processes die, the same ETS table lives on and is given to the processes when they restart.

This supervisor should also be a parent to the current executor process tree. That way, if the supervisor needs to restart, you know that all the children are dead anyway, so nobody is going to care that the tokens or memory service data are gone.

When creating a token, monitor the process that requests it (this will be an executor). When that process dies, that means it's either succeeded, failed, or crashed; in all cases, we want to get rid of the token. Same idea for memory service (but slightly different, since we're not going to have an Erlang PID coming in via HTTP. Maybe we store the executor PID in our token store, too? Seems like we'll need some clean way to map from token / executor ID to process.)

While the original description mentioned a time-based token expiration, this is actually unnecessarily complicated, particularly since the timeout we currently have is for a single command invocation and not for the pipeline as a whole. The monitor-based approach above will cover our bases, in any event.

For the Phoenix controller, we can create a new authentication plug. While we already have an authentication plug, this authentication will be different enough (different header structure, different backend storage for tokens) that extending it to handle both flows is likely not worth the trouble. Of course, if after implementing it separately there are obvious points of consolidation, we should take advantage of that. Also keep in mind that the existing authentication plug is used in a few "unique" cases (user trying to update themselves, header-based auth for triggers); any changes would need to still work in those cases, obviously.

Take advantage of our "repository" pattern (https://github.com/operable/cog/tree/master/lib/cog/repository) to create an interface for getting information about currently-provided services. For now, we'll simply return essentially hard-coded information about the memory (and later, exec) services, but once we have a more robust API for service manipulation, a "service repository" provides a nice interface for the rest of the system.

We can use similar compile-time tricks that we used for bundle verification schemas to expose Swagger data for our services. We can write JSON / YAML files for them, store them in priv, and let the compiler pull them into our "service repository" until the more robust API comes along (at which point, some kind of database-backed storage akin to what we do with bundles will likely be implemented).
