### ISSUE TITLE
Verification that Migrations has been executed

### ISSUE THREAD

**Issue by lhaskins** [operable/cog#363]
We should verify that the most recent migrations has been executed when starting a Cog instance.

**Comment by lhaskins** [comment]
The 'schema_migrations' table in the database has the version of the migration that has been migrated that correspond to the migration file names in "priv/repo/migrations".

**Comment by lhaskins** [comment]
The verification should take place after we verify that SMP and dirty_schedulers have been set.

**Comment by vanstee** [comment]
This might be sorta weird when actively working on a migration in dev since you could be migrating and rolling back to check things while the rolled-back migration file still exists. Maybe only enforcing this in the prod env would work? Although I don't think we're really using the prod env yet.

I know in Ecto 2.0 the schema will be dumped and stored on the file system after running each migration, so once we have that we'll know for sure whether or not our schema file matches up with the migration version in the db.
