### ISSUE TITLE
Add administration commands for relays and relay groups

### ISSUE THREAD

**Issue by imbriaco** [operable/cog#513]
The following administration activities for relays and relay_groups should be supported in the commands within the `operable` bundle. The the maximum extent possible, these should mirror the same actions in `cogctl`:

* List relays grouped by relay_group.
* Update name and/or description for a relay.
* Create/Rename/Delete relay_groups.
* Add/Remove relays to relay_groups.
* Assign/Unassign bundles to relay_groups.

Note: Relay creation and token update should not be exposed in the chat commands for now so that we don't leak the token.

**Comment by mpeck** [comment]
# Commands
## relays
```
Lists relays.
Usage: relays [--by-relay-group]

Examples:
me> relays
cog>  NAME     STATUS    CREATED AT             ID
      relay1   enabled   2016-04-27T13:23:33Z   e7ddd6e9-9ad1-4a13-83a2-2c993478654e
      relay2   enabled   2016-04-27T13:23:33Z   0e2a1a50-efea-487c-b1a9-bd2cb62d8df3
      relay3   disabled  2016-04-27T13:23:33Z   0872b713-9eef-4559-9ae2-4af55d2690ba
  
me> relays --by-relay-group
cog>  NAME     RELAY GROUP   STATUS    CREATED AT             ID
      relay1   group1        enabled   2016-04-27T13:23:33Z   e7ddd6e9-9ad1-4a13-83a2-2c993478654e
      relay3   group1,group2 enabled   2016-04-27T13:23:33Z   0872b713-9eef-4559-9ae2-4af55d2690ba
      relay2   group2        disabled  2016-04-27T13:23:33Z   0e2a1a50-efea-487c-b1a9-bd2cb62d8df3
```

JSON output
```
[{"name": "relay1",
  "status": "enabled",
  "created_at": "2016-04-27T13:23:33Z",
  "id": "e7ddd6e9-9ad1-4a13-83a2-2c993478654e",
  "description": "",
  "relay_groups": ["group1"], // only available if --by-relay-group is passed},
  ...]
```
As far as I can tell there is no way to list relays grouped by relay group in cogctl. Perhaps that's something we should add?

## relays update
```
Updates a relay.
Usage: relays update <relay_name> [--name][--description]

Examples:
me> relays update relay1 --name bigdaddy1
cog>  ok
```
JSON Output
```
{"status": "ok",
 "relay": { ... relay model ... }}
```
**Question:** Any thoughts on this? Since it's an update I'm just responding with an "ok" to the user so they know everything went ok. If there was an error we would return the error. But the json includes the full resource that was updated. I thought that could be potentially useful in a pipeline.

## relay-groups
Output based on `cogctl relay-groups`
```
Lists relay groups.
Usage: relay-groups

Examples:
me> relay-groups
cog>  NAME     CREATED               ID
      mygroup  2016-04-27T13:49:26Z  e2004b97-6539-416c-a612-20245218d0cc
```
JSON Output
```
[{"name": "mygroup",
  "created_at": "2016-04-27T13:49:26Z",
  "id": "e2004b97-6539-416c-a612-20245218d0cc"}]
```

## relay-groups create
```
Creates a relay group.
Usage: relay-groups create <group_name> [--members][--bundles]

Examples:
me> relay-groups create mygroup
cog>  ID    e2004b97-6539-416c-a612-20245218d0cc
      Name  mygroup
me> relay-groups create myothergroup --relays bigdaddy1
cog>  ID      5577c821-f0fd-46fa-b363-a3820bdbf1de
      Name    myothergroup
      Relays  bigdaddy1
```
JSON Output
```
{"name": "myouthergroup",
 "created_at": "2016-04-27T13:49:26Z",
  "id": "e2004b97-6539-416c-a612-20245218d0cc",
  "relays": [{ ... relay model ...},{...}], // Only available if --relays are specified
  "bundles": [{ ... bundle model ...},{...}] // Only available if --bundles are specified} 
```

## relay-groups rename
There does not seem to be a mechanism in cogctl for renaming relay groups.
```
Renames a relay group.
Usage: relay-groups rename <old_name> <new_name>

Examples:
me> relay-groups rename mygroup my_group
cog> ok
```
JSON Output
```
{"status": "ok",
 "relay-group": { ... relay group model ... }}
```
Note: Optionally we could use update instead of rename here. That might be more consistent with other resources. But, since there is only one thing you can change, I thought this would be clearer.

## relay-groups delete
```
Deletes a relay group.
Usage: relay-groups delete <group_name>

Examples:
me> relay-groups delete myothergroup
cog> ok
```
JSON Output
```
{"status": "ok",
 "relay_group": { ... relay group model ...}}
```

## relay-groups add
```
Adds relays to a relay group.
Usage: relay-groups add <group_name> <relay_names>

Examples:
me> relay-groups add mygroup relay1,relay2,relay3
cog> ok
```
JSON Output
```
{"status": "ok",
 "relay_group": {"name": "mygroup",
                          "created_at": "2016-04-27T13:49:26Z",
                          "id": "e2004b97-6539-416c-a612-20245218d0cc",
                          "relays": [{ ... relay model ... },{...}]}}
```

## relay-groups remove
```
Removes relays from relay-groups
Usage: relay-groups remove <group_name> <relay_names>

Example:
me>  relay-groups remove mygroup relay1,relay2
cog> ok
```
JSON Output
```
{"status": "ok",
 "relay_group": {"name": "mygroup",
                          "created_at": "2016-04-27T13:49:26Z",
                          "id": "e2004b97-6539-416c-a612-20245218d0cc",
                          "relays": [{ ... relay model ... },{...}]}}
```

## relay-groups assign
```
Assigns bundles to relay-groups
Usage: relay-groups assign <group_name> <bundle_names>

Example:
me> relay-groups assign mygroup bundle1,bundle2,bundle3
cog> ok
```
JSON Output
```
{"status": "ok",
 "relay_group": {"name": "mygroup",
                          "created_at": "2016-04-27T13:49:26Z",
                          "id": "e2004b97-6539-416c-a612-20245218d0cc",
                          "bundles": [{ ... bundle model ... },{...}]}}
```

## relay-groups unassign
```
Un-assigns bundles to relay-groups
Usage: relay-groups unassign <group_name> <bundle_names>

Example:
me> relay-groups unassign mygroup bundle1,bundle2
cog> ok
```
JSON Output
```
{"status": "ok",
 "relay_group": {"name": "mygroup",
                          "created_at": "2016-04-27T13:49:26Z",
                          "id": "e2004b97-6539-416c-a612-20245218d0cc",
                          "bundles": [{ ... bundle model ... },{...}]}}
```

**Comment by imbriaco** [comment]
These notes are all and idealized view, assuming we're working from a blank slate, and intentionally don't take into account fitting into the existing UX patterns for the operable bundle. 

That said:

1. Prefer singular names for commands. That is, I prefer `operable:relay` over `operable:relays` since the majority of the operations that you'll perform are against a singular relay resource and not against the aggregate of all relays.
2. Prefer a `list` action versus the implicit no-argument version returning the list. In a normal CLI utility I'd expect `relay` to list the available subcommands within that command and something like `relay list` to return the list of relays.
3. I think `--by-relay-group` in the `list` action is overly long and that a `--group` option would be equally intention revealing and much less typing.
4. I don't think we need `--members` or `--bundles` in `relay-group create`. I realize we added these in `cogctl`, but we primarily did that because the rest of the `cogctl` commands do not return output in a way that plays nicely in pipelines. I think leaning into more tightly focused commands that perform a single task and composing them with pipelines is the right approach.
5. `relay-group add/remove <group> <member1> .. <memberN>'. I prefer spaces over commas for the list of members. Same goes for `relay-group assign/unassign`.
6. In `relay list`, the list of relay groups can be arbitrarily long. This is a good reason to consider making it the last column in the table.
7. In most cases, the UUID and creation date are not useful information, but we always include them in output. I'd prefer to have a `--detail` option or have an `info` command for `relay` and `relay-group`. (ie:  `relay info <relay_name>`  or `relay list --detail`)
8. `relay update` should return a more human "Relay <name> has been updated." vs. "ok". Same idea everywhere this pattern occurs.
9. Would be useful to include relays and bundles in `relay-group list`, even if that means multiple lines per relay-group. This is similar to the `relay list` example above.

**Comment by kevsmith** [comment]
Support for short flag names would be nice too.

**Comment by mpeck** [comment]
Updates made sirs. One question. How does `[-v <verbose>]` instead of `[-d <details>]` sound to you for `relay/relay-group list`? I like either one, but we also have a description field on `relay update` that uses the `-d` short flag. They won't conflict of course, but I thought it might be clearer to the user if we didn't use the same short flag for different commands in the same group.

**Comment by christophermaier** [comment]
I kinda like `verbose` vs. `details`... seems more like all the CLI tools we use.

Also, I think the status bit in the JSON output might end up being noise since an actual error gets treated differently in the executor. I agree that `"Relay has been updated"` is more user-friendly than `"OK"`, but that seems like something that should live in the templates.
