### ISSUE TITLE
Add additional invocation data to cog_env

### ISSUE THREAD

**Issue by mpeck** [operable/cog#618]
In order to facilitate all commands being invoked as multi commands we need to include some additional information in their env.

There are two additional pieces required:
* `COG_STAGE_POS` - specifies where in the pipeline the command is being invoked. Can be one of three values [:first, nil, :last]
* `COG_INVOCATION_ID` - Specifies the unique id assigned to the pipeline segment being invoked.

Note: Embedded commands will receive the above data via `req.cog_env`. All embedded commands should now receive `cog_env`. Foreign commands will receive the data as env vars.

parent #399

**Comment by imbriaco** [comment]
Is `INVOCATION_ID` global to the pipeline or it it unique for each stage of the pipeline? I believe it's the latter since we already have `COG_PIPELINE_ID`. Also, make sure we expose this as `COG_INVOCATION_ID` in the environment. We need to be very consistent about namespacing our variables under `COG_`.

**Comment by mpeck** [comment]
Missed that bit @imbriaco issue updated.

**Comment by vanstee** [comment]
Instead of receiving this data in `req.cog_env`, we can include it in the `Cog.Command.Request` struct as `state_pos` and `invocation_id` which will still be translated to `COG_STATE_POS` and `COG_INVOCATION_ID` for foreign commands.

Also worth noting that we can reuse the `Invocation.id` provided by piper.

**Comment by vanstee** [comment]
* [ ] Add stage_pos to plan and command request on the cog side of things
* [ ] Deserialize the stage_pos part of the execution request and include it as COG_STAGE_POS for the command env if it exists
