### ISSUE TITLE
format:table command should accept paths, not just fields

### ISSUE THREAD

**Issue by christophermaier** [operable/cog#784]
Creating tables based on data from embedded objects should be possible.

You should also be able to specify your own custom headers to avoid long paths as column names.

**Comment by imbriaco** [comment]
Was curious so I quickly experimented with this. It turns out our normal field reference syntax is basically a subset of JSONPath (http://goessner.net/articles/JsonPath/), but without the leading `$.`. I've included a gist below that has some example of how this might work that can probably be adapted to the `table` command pretty easily.

It also does some optional mangling of field names:

* It uses the argument as the field name and the expression by default.
* If it sees an `=` in the argument, it sets the field name to be the left-hand-side and the expression to be the right-hand-side.
* If it sees a `.` it splits on `.` and sets the field name to be the last element of the list.

For both the `=` and `.` mangling, if the field name is already in use, it does not overwrite the existing name and uses the full argument as the field name instead.

https://gist.github.com/imbriaco/54ab242b04dccf346df3027bbd384ab1

**Comment by imbriaco** [comment]
Thinking about it, this might be useful as a more generic `format:extract` or similar that could be used in a pipeline more generally.

e.g.
```
my_command | format:extract id name child.id "foo[0].name" "child_bar_name=child.bars[0].name" "does_not_exist invalid" | format:table
```
