### ISSUE TITLE
Do not silently fail when command executable cannot be found

### ISSUE THREAD

**Issue by vanstee** [operable/cog#836]
After creating a native command and having it run an executable that didn't exist I just received the output: `Pipeline executed successfully, but no output was returned` which was confusing. We should return a more descriptive error if you get a non-zero status code and maybe even make sure that the executables exist before running them for a super descriptive error.

**Comment by kevsmith** [comment]
Requiring both stdout and stderr caused api.Result serialization to fail when both streams were empty. This condition was triggered when a command invocation resulted in an error due to Relay's mis-handling of errors returned from golang's os/exec.Process.Run(). Triggering this bug caused an encoding error (see circuit-driver/main.go:28-31) which subsequently caused the driver and container to exit.

From the user's PoV this error would present in two ways:

1. No error message when one should be displayed such as when config.yaml points to the wrong path for a command executable.

2. Truncated, missing, or empty output when output is expected. I think the most common occurrance would be missing log output.

This commit loosens field requirements on api.Result and also fixes Relay's bad error handling logic.
