### ISSUE TITLE
Return a better error message when dynamic config file cannot be parsed as yaml

### ISSUE THREAD

**Issue by vanstee** [operable/cog#867]
Currently cogctl responds with `cogctl: ERROR: "Internal server error"` if the yaml file could not be parsed as yaml (in this case an ENV var looking string was uploaded). We should make sure we just respond with `cogctl: ERROR: "Config file could not be parsed as yaml"`.

**Comment by christophermaier** [comment]
Further context: this was uncovered when a file with the contents

```
AWS_ACCESS_KEY_ID=XXX
AWS_SECRET_ACCESS_KEY=XXX
```
was uploaded via `cogctl`. Instead, it should have been the YAML

```yaml
AWS_ACCESS_KEY_ID: "XXX"
AWS_SECRET_ACCESS_KEY: "XXX"
```

Somehow, the contents of the first file made it to cog as a single string, instead of the map that was expected. This caused an Ecto changeset error, which resulted in the aforementioned "Internal server error".
