### ISSUE TITLE
Improve command error template

### ISSUE THREAD

**Issue by vanstee** [operable/cog#966]
Right now all of the important "specific error" information is hidden behind an attachment and generic debug information is displayed. We should reverse what is shown brining the specific error to the condensed version and keeping the debugging details behind a "show more..." link.

**Comment by mpeck** [comment]
This was pushed back due to some technical limitations. Right now errors are displayed within the body of an attachment. Attachments only show the first five lines of text. The rest is hidden behind a show more link.

Maybe we should look at a different method of presenting errors? Maybe using a snippet?

**Comment by agis-** [comment]
Wasn't https://github.com/operable/cog/pull/1181 related to this?

**Comment by vanstee** [comment]
Thanks @agis-. Closing this.
