### ISSUE TITLE
Support updating config.yaml in place

### ISSUE THREAD

**Issue by kevsmith** [operable/cog#969]
Put bluntly, command developers need to be able to iterate quickly when building new bundles or they'll find better uses for their time.

A major obstacle in the Cog development experience is the requirement to bump the bundle version in config.yaml, upload the new version, and then assign it to a relay group. This adds several steps and many minutes of latency to what should be a fairly quick process.

Cog should support updating an existing config.yaml "in place" such that the changes take effect immediately (or as quick as possible). There are a couple of questions to answer:

* How will Relay detect changes? Currently Relay's change detection relies entirely on the bundle version. Relay should continue to use bundle versions but also supplement with another recency check. Perhaps Cog could include a checksum of `config.yaml` in addition to the markup when Relay requests updates?
* Should this ability always be available or should it require a `-dev` switch on Cog?

Supports roadmap issue #882

**Comment by mpeck** [comment]
The problem is most apparent when doing template updates since that tends to be a very iterative process. I think the solution is that when we're in `dev` we do an update if the bundle record already exists. We can still use `cogctl` as normal to install. 

So the workflow would look something like:
...adjust the config.yaml...
`cogctl bundle install config.yaml`
...test the output...
repeat

I don't think we have to worry about relay in this case. As long as the image tag stays the same when building, you can iterate without having to worry about version bumps.
